output "id" {
  value = local.id
  description = "The ID of the resource"
}

output "labels" {
  value = local.labels
  description = "A Map of all Labels Generated by the Module"
}

output "labels_id" {
  value = local.labels_id
  description = "A Map of all 'Identity' Labels Generated by the Module."
}

output "labels_topology" {
  value = local.labels_topology
  description = "A Map of all 'Topology' Labels Generated by the Module."
}

output "labels_managed_by" {
  value = local.labels_managed_by
  description = "A Map of all 'Managed By' Labels Generated by the Module."
}


output "org" {
  value = var.org
  description = "The Organization Name"
}

output "org_short" {
  description = "Short Organization Name used for naming resources."
  value = var.org_short
}
output "org_tld" {
  description = "Organization TLD used to generate standard labels keys."
  value = var.org_tld
}

output "layer" {
  description = "Infrastructure layer of the resources, used to generate resource ID."
  value = var.layer
}

output "namespace" {
  description = "Namespace of generate resources, used to group resources of a team/sub-organization."
  value = var.namespace
}
output "stage" {
  description = "Stage of the resources, such as dev, test, prod, etc."
  value = var.stage
}
output "name" {
  description = "Name of the resources, used to generate resource ID."
  value = var.name
}
output "component" {
  description = "Sub-component of the resources, used to generate resource ID."
  value = var.component
}
output "region" {
  value = var.region
  description = "Region of the resources, used to generate resource ID."
}
output "zone" {
  value = var.zone
  description = "Zone of the resources if applicable."
}

output "managed_by" {
  value = var.managed_by
  description = "Name of the component that manages the resources. ( default to 'Terraform', possible values can be other IAC Tools if not managed by Terraform)"
}

output "managed_by_ref" {
  value = var.managed_by_ref
  description = "Reference of the location of the component that manages the resources. (Repo / Terraform State Path)"
}
